### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by amanuel1995** [amanuel1995/MI-449-SS17-741-html-terminal-and-git-_u9ftI#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://amanuel1995.github.io/MI-449-SS17-741-html-terminal-and-git-_u9ftI/) and meets the following criteria:

- [x] A knock-knock joke is displayed when visiting the website
- [x] The code is pushed to GitHub
- [x] The website is hosted on GitHub Pages

**Comment by stuartpearman** [comment]
Hey Amanuel, looks good! :shipit:
